### ISSUE TITLE
npm test gives different errors on each run

### ISSUE THREAD

**Issue by vserrao** [strongloop/loopback-workspace#253]
Hi,

I have cloned "loopback-workspace" from source. When I execute the "npm test" command in it, it is showing up different errors on each run. 

PFB the result of 4 consecutive runs. (as the upload was giving some issues, I had to paste it here.)

#####RUN 1#####
  124 passing (2m)
  2 pending
  3 failing

  1) end-to-end testConnection "before all" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  2) end-to-end start/stop/restart "before all" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  3) Facet Facet.create(def, cb) "before each" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

#####RUN 2#####

  43 passing (2m)
  10 failing

  1) end-to-end autoupdate updates a single model in the database:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  2) end-to-end autoupdate "before each" hook: resetMysqlDatabase:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  3) end-to-end autoupdate "after all" hook: closeConnection:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  4) end-to-end discovery "before all" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  5) end-to-end testConnection "before all" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  6) end-to-end start/stop/restart "before all" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  7) Facet Facet.create(def, cb) "before each" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  8) Middleware validates `name` uniqueness within the facet only:
     Uncaught AssertionError: expected undefined to include 'CUSTOM'
      at /root/valencia/loopback-workspace/test/end-to-end.js:271:29
      at Query._callback (/root/valencia/loopback-workspace/test/end-to-end.js:753:21)
      at Query.Sequence.end (/root/valencia/loopback-workspace/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at /root/valencia/loopback-workspace/node_modules/mysql/lib/protocol/Protocol.js:226:14
      at /root/valencia/loopback-workspace/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
      at doNTCallback0 (node.js:407:9)
      at process._tickDomainCallback (node.js:377:13)
      at process.<anonymous> (/root/valencia/loopback-workspace/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)

  9) Middleware middleware.configFile "before each" hook:
     Error: EEXIST: file already exists, mkdir '/root/valencia/loopback-workspace/test/sandbox'
      at Error (native)

  10) Middleware Middleware.create(def, cb) "before each" hook:
     Error: EEXIST: file already exists, mkdir '/root/valencia/loopback-workspace/test/sandbox'
      at Error (native)

#####RUN 3#####
128 passing (50s)
  2 pending
  4 failing

  1) end-to-end autoupdate "before all" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  2) end-to-end discovery "before all" hook:
     Error: EEXIST: file already exists, mkdir '/root/valencia/loopback-workspace/test/sandbox'
      at Error (native)

  3) end-to-end testConnection "before all" hook:
     Error: ENOTEMPTY: directory not empty, rmdir '/root/valencia/loopback-workspace/test/sandbox/server'
      at Error (native)

  4) end-to-end start/stop/restart "before all" hook:
     Error: ENOTEMPTY: directory not empty, rmdir '/root/valencia/loopback-workspace/test/sandbox'
      at Error (native)
	  
#####RUN 4#####
  116 passing (2m)
  2 pending
  5 failing

  1) end-to-end autoupdate "before each" hook: resetMysqlDatabase:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  2) end-to-end start/stop/restart "before all" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  3) Facet Facet.create(def, cb) "before each" hook:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  4) Middleware validates `name` uniqueness within the facet only:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/root/valencia/loopback-workspace/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)

  5) Middleware Middleware.create(def, cb) "before each" hook:
     Error: ENOTEMPTY: directory not empty, rmdir '/root/valencia/loopback-workspace/test/sandbox'
      at Error (native)

-------------------------------------------------------------------------------------------------------------------------
However, most of these failures are related to "timeout". 

If "timeout", is the cause of such behavior of each run then please guide me how to solve these "timeout" related issues.

Thanks, 
vserrao

**Comment by richardpringle** [comment]
@jannyHou, have you run into this issue before?

**Comment by jannyHou** [comment]
@richardpringle @vserrao run npm test in workspace needs some config for a valid mysql db. 
From @vserrao 's test results the config works fine, so the problem is `before all` hook.
This error happens with some repos, not only workspace, and the failing reason is always timeout. I once see it on my local but never on CI, I suppose it's caused by speed of system. Some system run a test case slower than the timeout limit(always happen when you create a sandbox app).

**Comment by richardpringle** [comment]
So @jannyHou, you have any solution for @vserrao? Can he change the timeout settings of the test or something to get it to pass? 

@vserrao, what's your goal here, are you trying to work on this repo to possibly submit a PR? If so, maybe we can get this issue bumped up in priority.

**Comment by jannyHou** [comment]
@richardpringle @vserrao Yeah, please try to increase the timeout limit.

**Comment by vserrao** [comment]
Hi.......sorry I couldn't reply sooner. Actually, I've moved to another high priority task. I'll get back to loopback-workspace as soon as possible. 

And yes I would like to submit a PR for it.

**Comment by richardpringle** [comment]
@jannyHou, did you confirm that this is a bug? If so can you add the label please :smile:

**Comment by jannyHou** [comment]
@richardpringle I didn't see any CI test fails due to timeout error lol, and actually we already increased timeout in some test case, like [end-to-end.js](https://github.com/strongloop/loopback-workspace/blob/master/test/end-to-end.js#L33)

@vserrao could you try to increase the timeout on your local and try again to see if it still fails? Thanks. Since our CI seems ok with the current timeout setup.

**Comment by jannyHou** [comment]
OOPS, just find a machine fails with same error, from pr https://github.com/strongloop/loopback-workspace/pull/299:
CI ubuntu-0.12
http://ci.strongloop.com/job/loopback-workspace/label=ubuntu-0.12/4504/console

label it as a bug.

**Comment by jannyHou** [comment]
Related pr: https://github.com/strongloop/loopback-workspace/pull/311

**Comment by 0candy** [comment]
@vserrao Are you still encountering this problem?

**Comment by jannyHou** [comment]
My local test all pass:
```
  189 passing (6m)
  2 pending


```
We can reopen this issue if it happens again or create a new issue to describe the new bug. Thanks.
