### ISSUE TITLE
slc loopback:model crashes when depending on git url

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-workspace#319]
Reported by @azatoth in https://github.com/strongloop/strongloop/issues/316:
 
Having a dependency for "loopback" to "https://github.com/strongloop/loopback.git#2.x" results in `slc loopback:model` to crash with following error:

```
/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:678
    throw new TypeError('Invalid comparator: ' + comp);
    ^

TypeError: Invalid comparator: https://github.com/strongloop/loopback.git#2.x
    at Comparator.parse (/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:678:11)
    at new Comparator (/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:662:8)
    at /usr/lib/node_modules/strongloop/node_modules/semver/semver.js:780:12
    at Array.map (native)
    at Range.parseRange (/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:779:13)
    at Range.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:721:17)
    at Array.map (native)
    at new Range (/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:720:40)
    at outside (/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:1132:11)
    at Function.gtr (/usr/lib/node_modules/strongloop/node_modules/semver/semver.js:1126:10)

```

**Comment by bajtos** [comment]
> Having a dependency for "loopback" to "https://github.com/strongloop/loopback.git#2.x" results in `slc loopback:model` to crash

@0candy PTAL. I think this is caused by this line: https://github.com/strongloop/loopback-workspace/blob/2cfab28e35b4ea7d962dc971339854eb7e678a4d/common/models/model-method.js#L17

```js
 return version != null ? !semver.gtr('3.0.0', version) : false;
```

**Comment by 0candy** [comment]
semver does not compare git url. Should set default loopback version if value is invalid for comparison.
https://github.com/strongloop/loopback-workspace/blob/master/server/connector.js#L218
